language: node_js
node_js:
- '4.2'
before_install: npm install -g grunt-cli
install: npm install
notifications:
  slack:
    secure: thS2DH2l15+QD9MffNQX41PD3nEig8NsiHGbjWyS22n4P1MYkkoAFTqHnhZnzPHe/gYBlOMPxrQCC/WzAFJ0MIXK1CXNm37JALTL6YCc9hlOTQIOXdKM7Ql7nmeNx9eeK8qrHBN0WQqUwKAtdMeFubHBZkpLCeh2ifPw0hNrEe6bAfYdLap/32m0zgr+2UF2KiljXjyvKktLLpRhJ0BAH2HHRIA8KnssN3suwNl/RKJ45ipcagxgEEF0mrZlPOsWYDVNCRj23bQDO1P5PaUlgrzo0zDOflfa8aIqJaqvB505E9cGzhV5TNtehHJt38LOt85ErSX9cejaVUpaS155+YLsWJpQzmt8I3m47DDnmFCEja2toszTga2fhopnPguulSt6b8zSP2SyOmSWawqO7RNLoV2hFpdU+Mw2BL62stuyAoTGfYya+Qw5y2Sd4cRY7hZJS6mFaSGKOKeRVndSeqEyHa8j9CpYkrHDTht6NbNRzPOWuYiVSwYNGX67dab3ApiQRUH+Rf8ubAyyuJKkUrUm5s/zaXyHoWhe0azYIPHBOtHh4e0BMda8kJNpDO7MTSv9WCIpRbk7Jb6vGrPrUIkyAel2DaCaO0UzzLMv6jjvXeYqZTW6K+CIRo6V4Rqj7odhMLvi1DlLaf0fjGoJIScP7/xKVpzYRyRt+DNx9OU=
