language: node_js
node_js:
- '4.2'
before_install: npm install -g grunt-cli
install: npm install
notifications:
  slack:
    secure: thS2DH2l15+QD9MffNQX41PD3nEig8NsiHGbjWyS22n4P1MYkkoAFTqHnhZnzPHe/gYBlOMPxrQCC/WzAFJ0MIXK1CXNm37JALTL6YCc9hlOTQIOXdKM7Ql7nmeNx9eeK8qrHBN0WQqUwKAtdMeFubHBZkpLCeh2ifPw0hNrEe6bAfYdLap/32m0zgr+2UF2KiljXjyvKktLLpRhJ0BAH2HHRIA8KnssN3suwNl/RKJ45ipcagxgEEF0mrZlPOsWYDVNCRj23bQDO1P5PaUlgrzo0zDOflfa8aIqJaqvB505E9cGzhV5TNtehHJt38LOt85ErSX9cejaVUpaS155+YLsWJpQzmt8I3m47DDnmFCEja2toszTga2fhopnPguulSt6b8zSP2SyOmSWawqO7RNLoV2hFpdU+Mw2BL62stuyAoTGfYya+Qw5y2Sd4cRY7hZJS6mFaSGKOKeRVndSeqEyHa8j9CpYkrHDTht6NbNRzPOWuYiVSwYNGX67dab3ApiQRUH+Rf8ubAyyuJKkUrUm5s/zaXyHoWhe0azYIPHBOtHh4e0BMda8kJNpDO7MTSv9WCIpRbk7Jb6vGrPrUIkyAel2DaCaO0UzzLMv6jjvXeYqZTW6K+CIRo6V4Rqj7odhMLvi1DlLaf0fjGoJIScP7/xKVpzYRyRt+DNx9OU=
after_success: bash ./site/deploy.sh
env:
  global:
  - GH_REF: github.com/ScottLogic/BitFlux.git
  - secure: YSvDn5LuTWE1ZqRtB3woUlrEtssLx4RAy8DpSChzrnBf5q4zV/AnSxfdtsqu0QqP7lpN6ZDz9A0sGKxEPT7MWQQ/YtzwR7CSlOIWulIPihMCw6yAkuDHwR4kSJaPvgWFEUPYZ8Mp7SVfWjxqexMJ0SGF+q/WCr976s+NHPMMhiAQgMfaauxSDnadvknS1mCEkCxFIPxTDl3mDqWMeVUJ5oY+bc5fOqVfOlwZ8zogm84FqbvdCQYfyeL6Aj7Yx96Szo23yEuDTdp9bNJFVXp63m6EmBC/+SG/3W+iKQXqkgmocf62mSaxnNA4e3eC5RWb1V3fRKyIVYDq//Jx/Nrx4NFYdad3Y8fS/i7V+gUAzpyKCZTb8CRu7fMqc763LHnZ7378e5ouPQvnPixe9SIAjsIBzex/yJzC94E7W2nI2g+c/FTUELl2qmvL2D2dGqzPRHg4FqIIrxZe7TlvrXpHc699w16OIcy0CckUdJFOFT41yx09SLQuQSbjzROdEY4QyJgJiHBQT0hp0s3EEghDLle9qjofFPbxN84CZsYvWjxSXaS9e0y+QmJupo88m6gtgjAYnZnogRxbRoqkvAz8X0ib15ZTeT7kOnHnCpEiDFj5Zos+kzeZgdxTlf3nj+1LkQXT53BGzgRMdUE8CSpE58855aqQ7wza78p+cA4n72w=
